# Generated by Django 4.1.2 on 2022-10-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_configuracion_subtitutulo_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=30)),
                ('nombre_apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
            ],
        ),
    ]
