# Generated by Django 4.1.2 on 2022-11-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_usuarios'),
        ('blog', '0005_post_image'),
    ]

    operations = [
    ]
