# Generated by Django 4.1.2 on 2022-11-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_merge_0004_usuarios_0005_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=20)),
                ('blog_subtitle', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Configuracion',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
