# Generated by Django 4.1.2 on 2022-10-28 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
